### YamlMime:ManagedReference
items:
- uid: Frent.Config
  commentId: T:Frent.Config
  id: Config
  parent: Frent
  children:
  - Frent.Config.#ctor(System.Int32,System.Boolean)
  - Frent.Config.MultiThreadedUpdate
  - Frent.Config.Multithreaded
  - Frent.Config.Singlethreaded
  - Frent.Config.ThreadCount
  langs:
  - csharp
  - vb
  name: Config
  nameWithType: Config
  fullName: Frent.Config
  type: Class
  source:
    remote:
      path: Frent/Config.cs
      branch: master
      repo: https://github.com/itsBuggingMe/Frent.git
    id: Config
    path: Config.cs
    startLine: 7
  assemblies:
  - Frent
  namespace: Frent
  summary: Config information for a <xref href="Frent.World" data-throw-if-not-resolved="false"></xref>
  example: []
  syntax:
    content: public class Config
    content.vb: Public Class Config
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Frent.Config.#ctor(System.Int32,System.Boolean)
  commentId: M:Frent.Config.#ctor(System.Int32,System.Boolean)
  id: '#ctor(System.Int32,System.Boolean)'
  parent: Frent.Config
  langs:
  - csharp
  - vb
  name: Config(int, bool)
  nameWithType: Config.Config(int, bool)
  fullName: Frent.Config.Config(int, bool)
  type: Constructor
  source:
    remote:
      path: Frent/Config.cs
      branch: master
      repo: https://github.com/itsBuggingMe/Frent.git
    id: .ctor
    path: Config.cs
    startLine: 7
  assemblies:
  - Frent
  namespace: Frent
  summary: Config information for a <xref href="Frent.World" data-throw-if-not-resolved="false"></xref>
  example: []
  syntax:
    content: public Config(int threadCount, bool multiThreadedUpdate)
    parameters:
    - id: threadCount
      type: System.Int32
      description: The number of threads to use when multithreading
    - id: multiThreadedUpdate
      type: System.Boolean
      description: Whether or not to multithread <xref href="Frent.World.Update" data-throw-if-not-resolved="false"></xref>
    content.vb: Public Sub New(threadCount As Integer, multiThreadedUpdate As Boolean)
  overload: Frent.Config.#ctor*
  nameWithType.vb: Config.New(Integer, Boolean)
  fullName.vb: Frent.Config.New(Integer, Boolean)
  name.vb: New(Integer, Boolean)
- uid: Frent.Config.ThreadCount
  commentId: P:Frent.Config.ThreadCount
  id: ThreadCount
  parent: Frent.Config
  langs:
  - csharp
  - vb
  name: ThreadCount
  nameWithType: Config.ThreadCount
  fullName: Frent.Config.ThreadCount
  type: Property
  source:
    remote:
      path: Frent/Config.cs
      branch: master
      repo: https://github.com/itsBuggingMe/Frent.git
    id: ThreadCount
    path: Config.cs
    startLine: 12
  assemblies:
  - Frent
  namespace: Frent
  summary: The number of threads to use when multithreading
  example: []
  syntax:
    content: public int ThreadCount { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property ThreadCount As Integer
  overload: Frent.Config.ThreadCount*
- uid: Frent.Config.MultiThreadedUpdate
  commentId: P:Frent.Config.MultiThreadedUpdate
  id: MultiThreadedUpdate
  parent: Frent.Config
  langs:
  - csharp
  - vb
  name: MultiThreadedUpdate
  nameWithType: Config.MultiThreadedUpdate
  fullName: Frent.Config.MultiThreadedUpdate
  type: Property
  source:
    remote:
      path: Frent/Config.cs
      branch: master
      repo: https://github.com/itsBuggingMe/Frent.git
    id: MultiThreadedUpdate
    path: Config.cs
    startLine: 16
  assemblies:
  - Frent
  namespace: Frent
  summary: Whether or not to multithread <xref href="Frent.World.Update" data-throw-if-not-resolved="false"></xref>
  example: []
  syntax:
    content: public bool MultiThreadedUpdate { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property MultiThreadedUpdate As Boolean
  overload: Frent.Config.MultiThreadedUpdate*
- uid: Frent.Config.Multithreaded
  commentId: P:Frent.Config.Multithreaded
  id: Multithreaded
  parent: Frent.Config
  langs:
  - csharp
  - vb
  name: Multithreaded
  nameWithType: Config.Multithreaded
  fullName: Frent.Config.Multithreaded
  type: Property
  source:
    remote:
      path: Frent/Config.cs
      branch: master
      repo: https://github.com/itsBuggingMe/Frent.git
    id: Multithreaded
    path: Config.cs
    startLine: 21
  assemblies:
  - Frent
  namespace: Frent
  summary: The default multithreaded config
  example: []
  syntax:
    content: public static Config Multithreaded { get; }
    parameters: []
    return:
      type: Frent.Config
    content.vb: Public Shared ReadOnly Property Multithreaded As Config
  overload: Frent.Config.Multithreaded*
- uid: Frent.Config.Singlethreaded
  commentId: P:Frent.Config.Singlethreaded
  id: Singlethreaded
  parent: Frent.Config
  langs:
  - csharp
  - vb
  name: Singlethreaded
  nameWithType: Config.Singlethreaded
  fullName: Frent.Config.Singlethreaded
  type: Property
  source:
    remote:
      path: Frent/Config.cs
      branch: master
      repo: https://github.com/itsBuggingMe/Frent.git
    id: Singlethreaded
    path: Config.cs
    startLine: 25
  assemblies:
  - Frent
  namespace: Frent
  summary: The default singlethreaded config
  example: []
  syntax:
    content: public static Config Singlethreaded { get; }
    parameters: []
    return:
      type: Frent.Config
    content.vb: Public Shared ReadOnly Property Singlethreaded As Config
  overload: Frent.Config.Singlethreaded*
references:
- uid: Frent.World
  commentId: T:Frent.World
  parent: Frent
  href: Frent.World.html
  name: World
  nameWithType: World
  fullName: Frent.World
- uid: Frent.World.Update
  commentId: M:Frent.World.Update
  href: Frent.World.html#Frent_World_Update
  name: Update()
  nameWithType: World.Update()
  fullName: Frent.World.Update()
  spec.csharp:
  - uid: Frent.World.Update
    name: Update
    href: Frent.World.html#Frent_World_Update
  - name: (
  - name: )
  spec.vb:
  - uid: Frent.World.Update
    name: Update
    href: Frent.World.html#Frent_World_Update
  - name: (
  - name: )
- uid: Frent
  commentId: N:Frent
  href: Frent.html
  name: Frent
  nameWithType: Frent
  fullName: Frent
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Frent.Config.#ctor*
  commentId: Overload:Frent.Config.#ctor
  href: Frent.Config.html#Frent_Config__ctor_System_Int32_System_Boolean_
  name: Config
  nameWithType: Config.Config
  fullName: Frent.Config.Config
  nameWithType.vb: Config.New
  fullName.vb: Frent.Config.New
  name.vb: New
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Frent.Config.ThreadCount*
  commentId: Overload:Frent.Config.ThreadCount
  href: Frent.Config.html#Frent_Config_ThreadCount
  name: ThreadCount
  nameWithType: Config.ThreadCount
  fullName: Frent.Config.ThreadCount
- uid: Frent.Config.MultiThreadedUpdate*
  commentId: Overload:Frent.Config.MultiThreadedUpdate
  href: Frent.Config.html#Frent_Config_MultiThreadedUpdate
  name: MultiThreadedUpdate
  nameWithType: Config.MultiThreadedUpdate
  fullName: Frent.Config.MultiThreadedUpdate
- uid: Frent.Config.Multithreaded*
  commentId: Overload:Frent.Config.Multithreaded
  href: Frent.Config.html#Frent_Config_Multithreaded
  name: Multithreaded
  nameWithType: Config.Multithreaded
  fullName: Frent.Config.Multithreaded
- uid: Frent.Config
  commentId: T:Frent.Config
  parent: Frent
  href: Frent.Config.html
  name: Config
  nameWithType: Config
  fullName: Frent.Config
- uid: Frent.Config.Singlethreaded*
  commentId: Overload:Frent.Config.Singlethreaded
  href: Frent.Config.html#Frent_Config_Singlethreaded
  name: Singlethreaded
  nameWithType: Config.Singlethreaded
  fullName: Frent.Config.Singlethreaded
